import dotenv from 'dotenv';
import mongoose from 'mongoose';
import { connectDB } from '../config/db.js';
import Admin from '../models/Admin.js';
import Category from '../models/Category.js';
import Product from '../models/Product.js';
import HomepageSection from '../models/HomepageSection.js';
import SiteSettings from '../models/SiteSettings.js';

dotenv.config();

const seedAll = async (isStandalone = false) => {
  try {
    if (mongoose.connection.readyState !== 1) {
      await connectDB();
    }

    console.log('[Seed] Clearing existing collections for fresh catalog setup...');
    await Admin.deleteMany({});
    await Category.deleteMany({});
    await Product.deleteMany({});
    await HomepageSection.deleteMany({});
    await SiteSettings.deleteMany({});

    // 1. Seed Administrative Accounts
    console.log('[Seed] Seeding administrative accounts...');
    const defaultAdmins = [
      {
        name: 'LightHut Administrator',
        email: (process.env.ADMIN_EMAIL || 'admin@lighthut.com').toLowerCase().trim(),
        password: process.env.ADMIN_PASSWORD || 'admin123456',
        role: 'admin',
      },
      {
        name: 'NiceLamp Administrator',
        email: 'admin@nicelamp.com',
        password: process.env.ADMIN_PASSWORD || 'admin123456',
        role: 'admin',
      }
    ];

    for (const adm of defaultAdmins) {
      const exists = await Admin.findOne({ email: adm.email });
      if (!exists) {
        await Admin.create(adm);
        console.log(`[Seed] Admin created: ${adm.email}`);
      }
    }

    // 2. Seed Categories
    console.log('[Seed] Seeding product categories...');
    const categoriesData = [
      // ── 1. WALL LAMP ─────────────────────────────────────
      {
        name: 'Wall Lamp',
        slug: 'wall-lamp',
        description: 'Decorative and functional wall-mounted lamps for every interior style.',
        image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 0,
        isActive: true,
        seoTitle: 'Wall Lamps – LED & E27 | NiceLamp',
        seoDescription: 'Shop LED and E27 wall lamps for modern, classic, and luxury interiors.',
      },
      {
        name: 'LED Wall Lamp',
        slug: 'led-wall-lamp',
        description: 'Energy-efficient LED wall lamps with sleek modern designs for living rooms, bedrooms, and corridors.',
        image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 1,
        isActive: true,
        seoTitle: 'LED Wall Lamps | NiceLamp',
        seoDescription: 'Browse our collection of high-efficiency LED wall lamps with premium finishes.',
      },
      {
        name: 'E27 Wall Lamp',
        slug: 'e27-wall-lamp',
        description: 'Classic E27 socket wall lamps compatible with standard bulbs – ideal for bedside and hallway use.',
        image: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 2,
        isActive: true,
        seoTitle: 'E27 Wall Lamps | NiceLamp',
        seoDescription: 'E27 wall lamps for classic and contemporary spaces.',
      },
      // ── 2. PENDANT LAMP ───────────────────────────────────
      {
        name: 'Pendant Lamp',
        slug: 'pendant-lamp',
        description: 'Statement hanging pendant lamps for dining rooms, kitchens, and reception areas.',
        image: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 10,
        isActive: true,
        seoTitle: 'Pendant Lamps – LED & E27 Hanging Lights | NiceLamp',
        seoDescription: 'Explore pendant lamps in LED and E27 variants for stylish suspended lighting.',
      },
      {
        name: 'LED Hanging Lamp',
        slug: 'led-hanging-lamp',
        description: 'Modern LED hanging pendant lamps with integrated drivers – zero maintenance, maximum style.',
        image: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 11,
        isActive: true,
        seoTitle: 'LED Hanging Lamps | NiceLamp',
        seoDescription: 'Energy-saving LED pendant lamps for dining, kitchen, and feature spaces.',
      },
      {
        name: 'E27 Hanging Lamp',
        slug: 'e27-hanging-lamp',
        description: 'Versatile E27 pendant lamps with decorative fabric cords and adjustable drop heights.',
        image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 12,
        isActive: true,
        seoTitle: 'E27 Hanging Lamps | NiceLamp',
        seoDescription: 'E27 socket pendant lamps compatible with decorative filament bulbs.',
      },
      // ── 3. CHANDELIER ────────────────────────────────────
      {
        name: 'Chandelier',
        slug: 'chandelier',
        description: 'Magnificent chandeliers for grand living rooms, lobbies, and luxury spaces.',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 20,
        isActive: true,
        seoTitle: 'Chandeliers – All Styles | NiceLamp',
        seoDescription: 'Discover LED, glass, Italian, antique, modern, and fan chandeliers at NiceLamp.',
      },
      {
        name: 'LED Chandelier',
        slug: 'led-chandelier',
        description: 'Integrated LED chandeliers offering brilliant illumination with ultra-low energy consumption.',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 21,
        isActive: true,
        seoTitle: 'LED Chandeliers | NiceLamp',
        seoDescription: 'LED chandeliers for luxury interiors with modern and classic designs.',
      },
      {
        name: 'E14 Chandelier',
        slug: 'e14-chandelier',
        description: 'Multi-arm E14 candelabra chandeliers with replaceable bulbs for a classic elegant look.',
        image: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 22,
        isActive: true,
        seoTitle: 'E14 Chandeliers | NiceLamp',
        seoDescription: 'E14 multi-arm chandeliers for dining rooms, foyers, and hotel lobbies.',
      },
      {
        name: 'Profile Chandelier',
        slug: 'profile-chandelier',
        description: 'Sleek linear profile chandeliers with architectural LED strips for modern interiors.',
        image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 23,
        isActive: true,
        seoTitle: 'Profile Chandeliers | NiceLamp',
        seoDescription: 'Linear profile LED chandeliers for contemporary dining and meeting rooms.',
      },
      {
        name: 'Glass Chandelier',
        slug: 'glass-chandelier',
        description: 'Handcrafted glass chandeliers with blown, ribbed, and crystal-clear glass elements.',
        image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 24,
        isActive: true,
        seoTitle: 'Glass Chandeliers | NiceLamp',
        seoDescription: 'Elegant glass chandeliers in modern, classic, and art-glass styles.',
      },
      {
        name: 'Italian Chandelier',
        slug: 'italian-chandelier',
        description: 'Artisan Italian-crafted chandeliers inspired by Venetian glass and European luxury traditions.',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 25,
        isActive: true,
        seoTitle: 'Italian Chandeliers | NiceLamp',
        seoDescription: 'Authentic Italian-style chandeliers for luxury homes, hotels, and palaces.',
      },
      {
        name: 'Modern Chandelier',
        slug: 'modern-chandelier',
        description: 'Contemporary geometric and sculptural chandeliers for minimalist and modern interiors.',
        image: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 26,
        isActive: true,
        seoTitle: 'Modern Chandeliers | NiceLamp',
        seoDescription: 'Sleek modern chandeliers in metal, acrylic, and mixed-material finishes.',
      },
      {
        name: 'Antique Chandelier',
        slug: 'antique-chandelier',
        description: 'Heritage-inspired antique finish chandeliers with classic ironwork, crystals, and candelabra arms.',
        image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 27,
        isActive: true,
        seoTitle: 'Antique Chandeliers | NiceLamp',
        seoDescription: 'Classic antique chandeliers for traditional and heritage interior spaces.',
      },
      {
        name: 'Fan Chandelier',
        slug: 'fan-chandelier',
        description: 'Ceiling fan chandeliers combining decorative lighting with powerful airflow for living rooms.',
        image: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 28,
        isActive: true,
        seoTitle: 'Fan Chandeliers | NiceLamp',
        seoDescription: 'Decorative fan chandeliers with integrated lighting for living rooms and bedrooms.',
      },
      {
        name: 'Ceiling Chandelier',
        slug: 'ceiling-chandelier',
        description: 'Flush and semi-flush ceiling chandeliers ideal for rooms with standard ceiling heights.',
        image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 29,
        isActive: true,
        seoTitle: 'Ceiling Chandeliers | NiceLamp',
        seoDescription: 'Flush and semi-flush ceiling chandeliers for standard-height rooms.',
      },
      // ── 4. DOUBLE HEIGHT ─────────────────────────────────
      {
        name: 'Double Height',
        slug: 'double-height',
        description: 'Dramatic large-scale chandeliers engineered for double-height foyers, stairwells, and grand halls.',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 30,
        isActive: true,
        seoTitle: 'Double Height Chandeliers | NiceLamp',
        seoDescription: 'Grand double-height crystal and modern chandeliers for luxury foyers and atriums.',
      },
      {
        name: 'Crystal Chandelier',
        slug: 'crystal-chandelier',
        description: 'Precision-cut K9 crystal chandeliers delivering spectacular prismatic light for grand double-height spaces.',
        image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 31,
        isActive: true,
        seoTitle: 'Crystal Chandeliers | NiceLamp',
        seoDescription: 'K9 crystal chandeliers for foyers, ballrooms, and luxury double-height spaces.',
      },
      {
        name: 'Modern Double Height Chandelier',
        slug: 'modern-double-height-chandelier',
        description: 'Architectural large-scale modern chandeliers designed for soaring ceilings and open-plan grand halls.',
        image: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 32,
        isActive: true,
        seoTitle: 'Modern Double Height Chandeliers | NiceLamp',
        seoDescription: 'Contemporary large-scale chandeliers for double-height and high-ceiling spaces.',
      },
      // ── 5. DINING TABLE LAMP ─────────────────────────────
      {
        name: 'Dining Table Lamp',
        slug: 'dining-table-lamp',
        description: 'Elegant table lamps designed to complement dining spaces with warm, welcoming illumination.',
        image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 40,
        isActive: true,
        seoTitle: 'Dining Table Lamps | NiceLamp',
        seoDescription: 'Premium dining table lamps with warm-white illumination for elegant dining experiences.',
      },
      // ── 6. OUTDOOR LIGHT ─────────────────────────────────
      {
        name: 'Outdoor Light',
        slug: 'outdoor-light',
        description: 'Weather-resistant outdoor lighting solutions for gates, facades, gardens, and pathways.',
        image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 50,
        isActive: true,
        seoTitle: 'Outdoor Lights – Gate & Wall | NiceLamp',
        seoDescription: 'Durable IP-rated outdoor lights for gates, walls, and exterior facades.',
      },
      {
        name: 'Gate Lamp',
        slug: 'gate-lamp',
        description: 'Classic and modern gate post lamps to elevate your entrance with style and security.',
        image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 51,
        isActive: true,
        seoTitle: 'Gate Lamps | NiceLamp',
        seoDescription: 'Decorative and durable gate post lamps for residential and commercial entrances.',
      },
      {
        name: 'Outdoor Wall Lamp',
        slug: 'outdoor-wall-lamp',
        description: 'IP65 weatherproof outdoor wall lamps for exterior facades, porches, and garden walls.',
        image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 52,
        isActive: true,
        seoTitle: 'Outdoor Wall Lamps | NiceLamp',
        seoDescription: 'Weatherproof outdoor wall lights for facades, porches, and garden areas.',
      },
      // ── 7. TABLE LAMP ────────────────────────────────────
      {
        name: 'Table Lamp',
        slug: 'table-lamp',
        description: 'Sculptural and functional table lamps for bedside, study, and living room accent lighting.',
        image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 60,
        isActive: true,
        seoTitle: 'Table Lamps | NiceLamp',
        seoDescription: 'Designer table lamps in ceramic, metal, glass, and wood for every interior.',
      },
      // ── 8. FLOOR LAMP ────────────────────────────────────
      {
        name: 'Floor Lamp',
        slug: 'floor-lamp',
        description: 'Statement floor lamps for living rooms, reading corners, and home office spaces.',
        image: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 70,
        isActive: true,
        seoTitle: 'Floor Lamps | NiceLamp',
        seoDescription: 'Premium floor lamps with arched, tripod, and column designs for modern interiors.',
      },
      // ── 9. LED FILAMENT BULB ─────────────────────────────
      {
        name: 'LED Filament Bulb',
        slug: 'led-filament-bulb',
        description: 'Vintage-style LED filament bulbs with warm Edison glow and modern energy efficiency.',
        image: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 80,
        isActive: true,
        seoTitle: 'LED Filament Bulbs | NiceLamp',
        seoDescription: 'Vintage Edison LED filament bulbs – warm glow, low energy, long life.',
      },
      // ── 10. SPARE PART ───────────────────────────────────
      {
        name: 'Spare Part',
        slug: 'spare-part',
        description: 'Replacement parts and accessories for lamps and chandeliers.',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 90,
        isActive: true,
        seoTitle: 'Spare Parts – Lamp Accessories | NiceLamp',
        seoDescription: 'Original spare parts including hanging bases, drivers, and lamp accessories.',
      },
      {
        name: 'Hanging Base',
        slug: 'hanging-base',
        description: 'Universal ceiling canopy bases and hanging hardware for pendant and chandelier installations.',
        image: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 91,
        isActive: true,
        seoTitle: 'Hanging Bases & Canopies | NiceLamp',
        seoDescription: 'Ceiling canopy bases, rose covers, and suspension hardware for chandeliers and pendants.',
      },
      {
        name: 'Spare Driver',
        slug: 'spare-driver',
        description: 'Replacement LED drivers and transformers compatible with a wide range of NiceLamp luminaires.',
        image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80',
        sortOrder: 92,
        isActive: true,
        seoTitle: 'LED Spare Drivers & Transformers | NiceLamp',
        seoDescription: 'OEM-compatible LED drivers and power supplies for NiceLamp fixtures.',
      },
    ];

    const createdCategories = await Category.insertMany(categoriesData);
    console.log(`[Seed] Created ${createdCategories.length} categories.`);

    const catMap = {};
    createdCategories.forEach((c) => {
      catMap[c.slug] = c._id;
    });

    // 3. Seed Products
    console.log('[Seed] Seeding NiceLamp product catalog...');
    const productsData = [
      // ── LED WALL LAMP ─────────────────────────────────────────────
      {
        name: 'NL-WL101 Slim LED Wall Lamp',
        slug: 'nl-wl101-slim-led-wall-lamp',
        sku: 'NL-WL101',
        category: catMap['led-wall-lamp'],
        shortDescription: 'Sleek linear LED wall lamp with a brushed gold frame and frosted acrylic diffuser.',
        description: 'The NL-WL101 brings a refined horizontal glow to feature walls, headboards, and corridor niches. Its micro-prismatic acrylic diffuser eliminates hotspots for a smooth, uniform luminous surface.',
        images: [
          { url: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1200&q=80', alt: 'NL-WL101 LED Wall Lamp', isCover: true },
        ],
        specifications: {
          dimensions: '600mm x 80mm x 55mm',
          material: 'Extruded Aluminum & Acrylic',
          finish: 'Brushed Champagne Gold',
          wattage: '16W Integrated LED',
          voltage: 'AC 100-240V 50/60Hz',
          colorTemperature: '3000K Warm White (CRI > 92)',
          ipRating: 'IP20 Indoor',
          installationType: 'Surface Wall Mount',
          beamAngle: '120° Diffuse',
          cri: 'Ra > 92',
          luminousFlux: '1450 Lumens',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      {
        name: 'NL-WL102 Round LED Halo Wall Light',
        slug: 'nl-wl102-round-led-halo-wall-light',
        sku: 'NL-WL102',
        category: catMap['led-wall-lamp'],
        shortDescription: 'Circular LED wall light with indirect 360° halo glow – perfect for bedroom feature walls.',
        description: 'Soft perimeter LED illumination wraps the circular disc, casting a warm halo against the wall. Die-cast aluminum body with a matte white powder coat ensures long-lasting durability.',
        images: [
          { url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80', alt: 'NL-WL102 Round Halo', isCover: true },
        ],
        specifications: {
          dimensions: 'Diameter: 300mm, Depth: 40mm',
          material: 'Die-Cast Aluminum',
          finish: 'Matte White',
          wattage: '12W Integrated LED',
          voltage: 'AC 100-240V',
          colorTemperature: '3000K / 4000K Switchable',
          ipRating: 'IP20 Indoor',
          installationType: 'Flush Wall Mount',
          beamAngle: 'Indirect 360° Halo',
          cri: 'Ra > 90',
          luminousFlux: '1000 Lumens',
        },
        isFeatured: false,
        isPublished: true,
        sortOrder: 1,
      },
      // ── E27 WALL LAMP ─────────────────────────────────────────────
      {
        name: 'NL-WL201 Brass E27 Swing-Arm Wall Lamp',
        slug: 'nl-wl201-brass-e27-swing-arm-wall-lamp',
        sku: 'NL-WL201',
        category: catMap['e27-wall-lamp'],
        shortDescription: 'Articulating swing-arm E27 wall lamp in hand-brushed satin brass – timeless bedside companion.',
        description: 'Inspired by mid-century European reading lamps, the NL-WL201 features a fully articulated swing arm and a conical shade in satin brass. Compatible with any standard E27 bulb up to 60W.',
        images: [
          { url: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1200&q=80', alt: 'NL-WL201 Brass E27 Wall Lamp', isCover: true },
        ],
        specifications: {
          dimensions: 'Arm Reach: 450mm, Shade Dia: 180mm',
          material: 'Solid Brass & Steel',
          finish: 'Satin Antique Brass',
          wattage: 'E27 Max 60W (Bulb Not Included)',
          voltage: 'AC 220-240V',
          colorTemperature: 'Depends on Bulb',
          ipRating: 'IP20 Indoor',
          installationType: 'Surface Wall Mount',
          beamAngle: 'Adjustable Directional',
          cri: 'Depends on Bulb',
          luminousFlux: 'Depends on Bulb',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      // ── LED HANGING LAMP ──────────────────────────────────────────
      {
        name: 'NL-PL101 Cone LED Pendant Lamp',
        slug: 'nl-pl101-cone-led-pendant-lamp',
        sku: 'NL-PL101',
        category: catMap['led-hanging-lamp'],
        shortDescription: 'Minimalist matte-black cone LED pendant with focused downlight beam – ideal for dining tables.',
        description: 'The NL-PL101 delivers focused warm illumination directly onto dining surfaces. Its seamless spun-aluminum cone in matte black hides the LED array completely for a clean, glare-free appearance.',
        images: [
          { url: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1200&q=80', alt: 'NL-PL101 Cone Pendant', isCover: true },
        ],
        specifications: {
          dimensions: 'Shade Dia: 250mm, Height: 220mm, Cord: 1500mm adj.',
          material: 'Spun Aluminum',
          finish: 'Matte Black',
          wattage: '15W Integrated LED',
          voltage: 'AC 100-240V',
          colorTemperature: '3000K Warm White',
          ipRating: 'IP20 Indoor',
          installationType: 'Ceiling Pendant',
          beamAngle: '90° Direct Downlight',
          cri: 'Ra > 92',
          luminousFlux: '1350 Lumens',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      {
        name: 'NL-PL102 Geometric LED Cluster Pendant',
        slug: 'nl-pl102-geometric-led-cluster-pendant',
        sku: 'NL-PL102',
        category: catMap['led-hanging-lamp'],
        shortDescription: 'Three-head geometric LED pendant cluster in gold – perfect over kitchen islands.',
        description: 'A trio of hexagonal LED heads suspended on individual cords from a shared ceiling rose. Each head angle is adjustable, allowing you to tailor light distribution over breakfast bars and kitchen islands.',
        images: [
          { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', alt: 'NL-PL102 Cluster Pendant', isCover: true },
        ],
        specifications: {
          dimensions: 'Canopy: 150mm Dia, Individual Head: 120mm',
          material: 'Aluminum Alloy',
          finish: 'Brushed Gold',
          wattage: '3 x 8W LED (24W Total)',
          voltage: 'AC 100-240V',
          colorTemperature: '3000K Warm White',
          ipRating: 'IP20 Indoor',
          installationType: 'Ceiling Cluster Pendant',
          beamAngle: '60° Each Head',
          cri: 'Ra > 90',
          luminousFlux: '2100 Lumens',
        },
        isFeatured: false,
        isPublished: true,
        sortOrder: 1,
      },
      // ── E27 HANGING LAMP ──────────────────────────────────────────
      {
        name: 'NL-PL201 Rattan E27 Globe Pendant',
        slug: 'nl-pl201-rattan-e27-globe-pendant',
        sku: 'NL-PL201',
        category: catMap['e27-hanging-lamp'],
        shortDescription: 'Handwoven natural rattan globe pendant with E27 socket – bohemian warmth for any room.',
        description: 'Each NL-PL201 globe is individually woven by hand from sustainable rattan. The open weave creates beautiful dappled light patterns on walls and ceilings when paired with a warm Edison filament bulb.',
        images: [
          { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80', alt: 'NL-PL201 Rattan Globe', isCover: true },
        ],
        specifications: {
          dimensions: 'Globe Dia: 300mm, Cord: 2000mm adj.',
          material: 'Natural Rattan & Jute Cord',
          finish: 'Natural Brown',
          wattage: 'E27 Max 40W (Bulb Not Included)',
          voltage: 'AC 220-240V',
          colorTemperature: 'Depends on Bulb',
          ipRating: 'IP20 Indoor',
          installationType: 'Ceiling Pendant',
          beamAngle: '360° Omnidirectional',
          cri: 'Depends on Bulb',
          luminousFlux: 'Depends on Bulb',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      // ── LED CHANDELIER ────────────────────────────────────────────
      {
        name: 'NL-CH101 Sputnik LED Chandelier',
        slug: 'nl-ch101-sputnik-led-chandelier',
        sku: 'NL-CH101',
        category: catMap['led-chandelier'],
        shortDescription: 'Mid-century Sputnik-style 12-arm LED chandelier in matte black and gold tips.',
        description: 'Twelve radiating arms extend in every direction from the central sphere, each tipped with a precision LED capsule. Makes a bold architectural statement in living rooms, hotel lobbies, and restaurant interiors.',
        images: [
          { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', alt: 'NL-CH101 Sputnik LED Chandelier', isCover: true },
        ],
        specifications: {
          dimensions: 'Spread: 800mm Dia, Height: 700mm',
          material: 'Steel & Aluminum',
          finish: 'Matte Black with Gold Tips',
          wattage: '12 x 5W G9 LED (60W Total)',
          voltage: 'AC 100-240V',
          colorTemperature: '3000K Warm White',
          ipRating: 'IP20 Indoor',
          installationType: 'Ceiling Mount with Steel Cable',
          beamAngle: 'Multi-Directional',
          cri: 'Ra > 90',
          luminousFlux: '5400 Lumens',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      // ── E14 CHANDELIER ────────────────────────────────────────────
      {
        name: 'NL-CH201 Classic 8-Arm E14 Chandelier',
        slug: 'nl-ch201-classic-8-arm-e14-chandelier',
        sku: 'NL-CH201',
        category: catMap['e14-chandelier'],
        shortDescription: 'Traditional 8-arm candelabra chandelier in antique gold with E14 candle-style sockets.',
        description: 'A masterpiece of classical European design. Eight graceful curved arms radiate from a central column, each terminating in a decorative drip canopy and E14 socket for candelabra LED bulbs.',
        images: [
          { url: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1200&q=80', alt: 'NL-CH201 Classic E14 Chandelier', isCover: true },
        ],
        specifications: {
          dimensions: 'Spread: 700mm Dia, Height: 600mm',
          material: 'Cast Iron & Zinc Alloy',
          finish: 'Antique Gold Electroplate',
          wattage: '8 x E14 Max 25W (Bulbs Not Included)',
          voltage: 'AC 220-240V',
          colorTemperature: 'Depends on Bulb',
          ipRating: 'IP20 Indoor',
          installationType: 'Ceiling Chain Suspension',
          beamAngle: 'Omnidirectional',
          cri: 'Depends on Bulb',
          luminousFlux: 'Depends on Bulb',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      // ── PROFILE CHANDELIER ────────────────────────────────────────
      {
        name: 'NL-CH301 Linear Profile LED Chandelier',
        slug: 'nl-ch301-linear-profile-led-chandelier',
        sku: 'NL-CH301',
        category: catMap['profile-chandelier'],
        shortDescription: 'Ultra-slim 1200mm linear LED profile chandelier with dimmable warm-white output.',
        description: 'A razor-sharp luminous line suspended above dining and conference tables. The extruded aluminum profile houses a high-density LED strip behind a micro-prismatic diffuser, producing a seamless luminous surface.',
        images: [
          { url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80', alt: 'NL-CH301 Linear Profile Chandelier', isCover: true },
        ],
        specifications: {
          dimensions: '1200mm x 60mm x 60mm',
          material: 'Extruded Aluminum',
          finish: 'Matte Black / Brushed Gold',
          wattage: '36W Integrated LED',
          voltage: 'AC 100-240V (Dimmable)',
          colorTemperature: '3000K Warm White',
          ipRating: 'IP20 Indoor',
          installationType: 'Wire Suspension (Aircraft Cable)',
          beamAngle: '120° Diffuse Downlight',
          cri: 'Ra > 95',
          luminousFlux: '3200 Lumens',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      // ── GLASS CHANDELIER ──────────────────────────────────────────
      {
        name: 'NL-CH401 Blown Glass Orb Chandelier',
        slug: 'nl-ch401-blown-glass-orb-chandelier',
        sku: 'NL-CH401',
        category: catMap['glass-chandelier'],
        shortDescription: 'Seven mouth-blown frosted glass orbs cascading at varying heights from a brushed nickel canopy.',
        description: 'Each globe is individually mouth-blown by skilled artisans, meaning no two are exactly alike. The cluster creates an organic, cloud-like composition that transforms any living room or foyer.',
        images: [
          { url: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1200&q=80', alt: 'NL-CH401 Glass Orb Chandelier', isCover: true },
        ],
        specifications: {
          dimensions: 'Canopy: 500mm Dia, Drop: up to 3000mm',
          material: 'Mouth-Blown Borosilicate Glass & Nickel',
          finish: 'Frosted White / Brushed Nickel',
          wattage: '7 x 5W G9 LED (35W Total)',
          voltage: 'AC 100-240V',
          colorTemperature: '2700K Warm Amber',
          ipRating: 'IP20 Indoor',
          installationType: 'High Ceiling Canopy Mount',
          beamAngle: 'Omnidirectional',
          cri: 'Ra > 92',
          luminousFlux: '3150 Lumens',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      // ── ITALIAN CHANDELIER ────────────────────────────────────────
      {
        name: 'NL-CH501 Murano-Style Italian Chandelier',
        slug: 'nl-ch501-murano-style-italian-chandelier',
        sku: 'NL-CH501',
        category: catMap['italian-chandelier'],
        shortDescription: 'Venetian art-glass chandelier with hand-applied gold leaf detailing on each glass petal.',
        description: 'Crafted following authentic Venetian glassmaking traditions, the NL-CH501 features an explosion of delicate glass flowers and leaves radiating from a gilded steel chassis.',
        images: [
          { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', alt: 'NL-CH501 Italian Murano Chandelier', isCover: true },
        ],
        specifications: {
          dimensions: 'Dia: 900mm, Fixture Height: 800mm, Drop: 4500mm max',
          material: 'Venetian Art Glass & Gilded Steel',
          finish: 'Gold Leaf & Multi-Colour Glass',
          wattage: '12 x E14 Max 25W (Bulbs Not Included)',
          voltage: 'AC 220-240V',
          colorTemperature: 'Depends on Bulb',
          ipRating: 'IP20 Indoor',
          installationType: 'Reinforced Ceiling Mount',
          beamAngle: 'Omnidirectional',
          cri: 'Depends on Bulb',
          luminousFlux: 'Depends on Bulb',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      // ── MODERN CHANDELIER ─────────────────────────────────────────
      {
        name: 'NL-CH601 Geometric Ring Modern Chandelier',
        slug: 'nl-ch601-geometric-ring-modern-chandelier',
        sku: 'NL-CH601',
        category: catMap['modern-chandelier'],
        shortDescription: 'Concentric ring LED chandelier in brushed gold – the ultimate modern statement piece.',
        description: 'Three concentric circular LED rings suspended at staggered heights create a mesmerising orbital effect. Warm-white LED strips are factory-dimmable for living rooms, open-plan spaces, and hotel lobbies.',
        images: [
          { url: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1200&q=80', alt: 'NL-CH601 Ring Chandelier', isCover: true },
        ],
        specifications: {
          dimensions: 'Outer Ring: 800mm Dia, Height: 500mm',
          material: 'Steel & Aluminum',
          finish: 'Brushed Gold',
          wattage: '72W Integrated LED',
          voltage: 'AC 100-240V (Dimmable)',
          colorTemperature: '3000K Warm White',
          ipRating: 'IP20 Indoor',
          installationType: 'Aircraft Cable Ceiling Mount',
          beamAngle: '360° Ring Diffuse',
          cri: 'Ra > 90',
          luminousFlux: '6200 Lumens',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      // ── ANTIQUE CHANDELIER ────────────────────────────────────────
      {
        name: 'NL-CH701 Wrought Iron Antique Chandelier',
        slug: 'nl-ch701-wrought-iron-antique-chandelier',
        sku: 'NL-CH701',
        category: catMap['antique-chandelier'],
        shortDescription: 'Hand-forged wrought iron antique chandelier with 6 candelabra arms and distressed bronze finish.',
        description: 'Reminiscent of grand heritage manor houses. The NL-CH701 is hand-forged from solid wrought iron and individually distressed by artisans to achieve its authentic aged bronze patina.',
        images: [
          { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80', alt: 'NL-CH701 Antique Iron Chandelier', isCover: true },
        ],
        specifications: {
          dimensions: 'Spread: 650mm Dia, Height: 550mm',
          material: 'Hand-Forged Wrought Iron',
          finish: 'Distressed Antique Bronze',
          wattage: '6 x E14 Max 40W (Bulbs Not Included)',
          voltage: 'AC 220-240V',
          colorTemperature: 'Depends on Bulb',
          ipRating: 'IP20 Indoor',
          installationType: 'Chain Ceiling Mount',
          beamAngle: 'Omnidirectional',
          cri: 'Depends on Bulb',
          luminousFlux: 'Depends on Bulb',
        },
        isFeatured: false,
        isPublished: true,
        sortOrder: 0,
      },
      // ── FAN CHANDELIER ────────────────────────────────────────────
      {
        name: 'NL-CH801 Crystal Fan Chandelier',
        slug: 'nl-ch801-crystal-fan-chandelier',
        sku: 'NL-CH801',
        category: catMap['fan-chandelier'],
        shortDescription: '52" decorative ceiling fan with K9 crystal chandelier skirt and dimmable LED light kit.',
        description: 'The NL-CH801 blends the cool airflow of a 52-inch high-efficiency fan with the grandeur of a crystal chandelier. Six reversible blades and remote-controlled dimming for master bedrooms and living rooms.',
        images: [
          { url: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1200&q=80', alt: 'NL-CH801 Crystal Fan Chandelier', isCover: true },
        ],
        specifications: {
          dimensions: 'Blade Span: 52 inch (1320mm)',
          material: 'Steel Motor Housing & K9 Crystal Trim',
          finish: 'Brushed Chrome & Clear Crystal',
          wattage: '65W Motor + 30W LED Light Kit',
          voltage: 'AC 220V 50Hz',
          colorTemperature: '3000K Warm White',
          ipRating: 'IP20 Indoor',
          installationType: 'Ceiling Direct Mount or Downrod',
          beamAngle: 'Downward Diffuse',
          cri: 'Ra > 80',
          luminousFlux: '2700 Lumens (Light Kit)',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      // ── CEILING CHANDELIER ────────────────────────────────────────
      {
        name: 'NL-CH901 Flush Mount Ceiling Chandelier',
        slug: 'nl-ch901-flush-mount-ceiling-chandelier',
        sku: 'NL-CH901',
        category: catMap['ceiling-chandelier'],
        shortDescription: 'Semi-flush ceiling chandelier with frosted glass shade and chrome detailing – suits 8-9ft ceilings.',
        description: 'Perfect for rooms where a hanging chandelier is impractical. The NL-CH901 sits close to the ceiling providing a chandelier-like aesthetic without requiring a high ceiling.',
        images: [
          { url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80', alt: 'NL-CH901 Flush Mount Chandelier', isCover: true },
        ],
        specifications: {
          dimensions: 'Dia: 500mm, Height: 300mm (from ceiling)',
          material: 'Steel & Frosted Glass',
          finish: 'Chrome & Frosted White',
          wattage: '4 x E14 Max 25W (Bulbs Not Included)',
          voltage: 'AC 220-240V',
          colorTemperature: 'Depends on Bulb',
          ipRating: 'IP20 Indoor',
          installationType: 'Semi-Flush Ceiling Mount',
          beamAngle: 'Omnidirectional',
          cri: 'Depends on Bulb',
          luminousFlux: 'Depends on Bulb',
        },
        isFeatured: false,
        isPublished: true,
        sortOrder: 0,
      },
      // ── CRYSTAL CHANDELIER (DOUBLE HEIGHT) ────────────────────────
      {
        name: 'NL-DH101 Grand K9 Crystal Chandelier',
        slug: 'nl-dh101-grand-k9-crystal-chandelier',
        sku: 'NL-DH101',
        category: catMap['crystal-chandelier'],
        shortDescription: 'Cascading 5-tier K9 crystal chandelier for double-height foyers and ballrooms.',
        description: 'The NL-DH101 is the crown jewel of our chandelier collection. Five cascading tiers of precision-cut K9 crystal prisms capture every light ray and scatter it into thousands of glittering rainbow reflections.',
        images: [
          { url: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1200&q=80', alt: 'NL-DH101 Grand Crystal Chandelier', isCover: true },
          { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', alt: 'Crystal Detail View', isCover: false },
        ],
        specifications: {
          dimensions: 'Dia: 1200mm, Fixture Height: 1500mm, Drop: 6000mm max',
          material: 'K9 Optical Crystal & Chromed Steel Frame',
          finish: 'Chrome & Clear Crystal',
          wattage: '24 x E14 Max 40W (Bulbs Not Included)',
          voltage: 'AC 220-240V',
          colorTemperature: 'Depends on Bulb',
          ipRating: 'IP20 Indoor',
          installationType: 'Reinforced Ceiling Plate (Structural Hook)',
          beamAngle: 'Prismatic Multi-Directional',
          cri: 'Depends on Bulb',
          luminousFlux: 'Depends on Bulb',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      {
        name: 'NL-DH102 Grand Raindrop Crystal Chandelier',
        slug: 'nl-dh102-grand-raindrop-crystal-chandelier',
        sku: 'NL-DH102',
        category: catMap['crystal-chandelier'],
        shortDescription: 'Cascading raindrop K9 crystal chandelier – 1500mm Dia, ideal for grand ballrooms.',
        description: 'Thousands of tear-drop cut crystal prisms descend like a shimmering rainfall from a polished chrome ceiling plate. Each prism is individually hand-strung and contributes to an overwhelming spectacle of reflected light.',
        images: [
          { url: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1200&q=80', alt: 'NL-DH102 Raindrop Crystal Chandelier', isCover: true },
        ],
        specifications: {
          dimensions: 'Dia: 1500mm, Drop: 8000mm max',
          material: 'K9 Crystal & Chrome Steel',
          finish: 'Chrome & Raindrop Crystal',
          wattage: '36 x E14 Max 40W',
          voltage: 'AC 220-240V',
          colorTemperature: 'Depends on Bulb',
          ipRating: 'IP20 Indoor',
          installationType: 'Structural Ceiling Hook',
          beamAngle: 'Prismatic Omnidirectional',
          cri: 'Depends on Bulb',
          luminousFlux: 'Depends on Bulb',
        },
        isFeatured: false,
        isPublished: true,
        sortOrder: 1,
      },
      // ── MODERN DOUBLE HEIGHT CHANDELIER ───────────────────────────
      {
        name: 'NL-DH201 Helix Modern Double Height Chandelier',
        slug: 'nl-dh201-helix-modern-double-height-chandelier',
        sku: 'NL-DH201',
        category: catMap['modern-double-height-chandelier'],
        shortDescription: 'Dramatic helical LED chandelier sculpture for soaring double-height spaces – 3m drop.',
        description: 'A sculptural helix of illuminated LED rings spirals downwards from the ceiling plate, creating a dynamic focal point in grand staircases, atrium lobbies, and contemporary mansions.',
        images: [
          { url: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1200&q=80', alt: 'NL-DH201 Helix Chandelier', isCover: true },
        ],
        specifications: {
          dimensions: 'Dia: 600mm, Drop: 3000mm (customisable)',
          material: 'Precision Steel & Aluminum',
          finish: 'Matte Black / Brushed Gold',
          wattage: '120W Integrated LED',
          voltage: 'AC 100-240V',
          colorTemperature: '3000K Warm White (Dimmable)',
          ipRating: 'IP20 Indoor',
          installationType: 'Structural Ceiling Mount',
          beamAngle: '360° Spiral Diffuse',
          cri: 'Ra > 90',
          luminousFlux: '10000 Lumens',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      // ── DINING TABLE LAMP ─────────────────────────────────────────
      {
        name: 'NL-DTL101 Ceramic Dining Table Lamp',
        slug: 'nl-dtl101-ceramic-dining-table-lamp',
        sku: 'NL-DTL101',
        category: catMap['dining-table-lamp'],
        shortDescription: 'Hand-thrown ceramic dining table lamp with linen drum shade and warm-white LED bulb.',
        description: 'Each ceramic base is thrown by hand on the potter\'s wheel, giving it a unique tactile surface. Paired with a natural linen drum shade, the NL-DTL101 casts warm, diffused light perfect for dining sideboards and buffets.',
        images: [
          { url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80', alt: 'NL-DTL101 Ceramic Dining Lamp', isCover: true },
        ],
        specifications: {
          dimensions: 'Height: 520mm, Shade Dia: 300mm',
          material: 'Hand-Thrown Ceramic & Linen',
          finish: 'Matte Ivory Glaze & Natural Linen',
          wattage: 'E27 Max 25W (LED Bulb Included)',
          voltage: 'AC 220-240V',
          colorTemperature: '2700K Warm White',
          ipRating: 'IP20 Indoor',
          installationType: 'Freestanding Table Lamp',
          beamAngle: '360° Diffuse',
          cri: 'Ra > 90',
          luminousFlux: '800 Lumens',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      // ── GATE LAMP ─────────────────────────────────────────────────
      {
        name: 'NL-OD101 Victorian Gate Post Lamp',
        slug: 'nl-od101-victorian-gate-post-lamp',
        sku: 'NL-OD101',
        category: catMap['gate-lamp'],
        shortDescription: 'IP44 Victorian-style lantern gate lamp in matte black cast aluminum – suits pillars and posts.',
        description: 'The NL-OD101 reinterprets the classic gas lantern in durable powder-coated cast aluminum. Its clear seeded glass panels and black ironwork provide an elegant first impression at residential gateways and driveways.',
        images: [
          { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80', alt: 'NL-OD101 Victorian Gate Lamp', isCover: true },
        ],
        specifications: {
          dimensions: '220mm x 220mm x 400mm (H)',
          material: 'Die-Cast Aluminum & Clear Glass',
          finish: 'Matte Black Powder Coat',
          wattage: 'E27 Max 60W (Bulb Not Included)',
          voltage: 'AC 220-240V',
          colorTemperature: 'Depends on Bulb',
          ipRating: 'IP44 Outdoor',
          installationType: 'Post Top / Wall Surface Mount',
          beamAngle: 'Omnidirectional',
          cri: 'Depends on Bulb',
          luminousFlux: 'Depends on Bulb',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      {
        name: 'NL-OD102 Modern Pillar Gate Light',
        slug: 'nl-od102-modern-pillar-gate-light',
        sku: 'NL-OD102',
        category: catMap['gate-lamp'],
        shortDescription: 'Sleek rectangular LED gate pillar light in anthracite – suits modern villas and bungalows.',
        description: 'Clean architectural lines make the NL-OD102 the perfect companion for contemporary residential gate pillars. Integrated LED strips on two faces provide balanced, glare-free illumination of the entrance.',
        images: [
          { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', alt: 'NL-OD102 Modern Pillar Gate Light', isCover: true },
        ],
        specifications: {
          dimensions: '150mm x 150mm x 500mm (H)',
          material: 'Die-Cast Aluminum',
          finish: 'Textured Anthracite',
          wattage: '2 x 6W LED (12W Total)',
          voltage: 'AC 100-240V',
          colorTemperature: '3000K Warm White',
          ipRating: 'IP65 Outdoor',
          installationType: 'Pillar Top Mount',
          beamAngle: 'Dual 120° Side Emission',
          cri: 'Ra > 80',
          luminousFlux: '1000 Lumens',
        },
        isFeatured: false,
        isPublished: true,
        sortOrder: 1,
      },
      // ── OUTDOOR WALL LAMP ─────────────────────────────────────────
      {
        name: 'NL-OD201 IP65 LED Outdoor Wall Light',
        slug: 'nl-od201-ip65-led-outdoor-wall-light',
        sku: 'NL-OD201',
        category: catMap['outdoor-wall-lamp'],
        shortDescription: 'Weatherproof LED outdoor wall light with motion sensor – ideal for porches and facades.',
        description: 'IP65-rated for full protection against water jets and dust ingress. The integrated PIR motion sensor activates the light upon detecting movement within a 10-metre range, enhancing both security and convenience.',
        images: [
          { url: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1200&q=80', alt: 'NL-OD201 Outdoor LED Wall Light', isCover: true },
        ],
        specifications: {
          dimensions: '200mm x 120mm x 90mm',
          material: 'Die-Cast Aluminum',
          finish: 'Textured Anthracite Grey',
          wattage: '18W Integrated LED',
          voltage: 'AC 100-240V',
          colorTemperature: '4000K Cool White',
          ipRating: 'IP65 Outdoor',
          installationType: 'Exterior Surface Wall Mount',
          beamAngle: '120° Wide',
          cri: 'Ra > 80',
          luminousFlux: '1600 Lumens',
        },
        isFeatured: false,
        isPublished: true,
        sortOrder: 0,
      },
      // ── TABLE LAMP ────────────────────────────────────────────────
      {
        name: 'NL-TL101 Marble & Brass Table Lamp',
        slug: 'nl-tl101-marble-brass-table-lamp',
        sku: 'NL-TL101',
        category: catMap['table-lamp'],
        shortDescription: 'Solid white marble base with polished brass stem and ivory pleated shade.',
        description: 'The combination of genuine Carrara white marble and hand-polished brass creates a sophisticated statement piece. The custom-crafted ivory pleated shade softens and diffuses light for a warm, inviting ambience.',
        images: [
          { url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80', alt: 'NL-TL101 Marble Table Lamp', isCover: true },
        ],
        specifications: {
          dimensions: 'Height: 580mm, Shade Dia: 320mm',
          material: 'Carrara Marble & Solid Brass',
          finish: 'Natural White Marble / Polished Brass',
          wattage: 'E27 Max 25W (LED Bulb Included)',
          voltage: 'AC 220-240V',
          colorTemperature: '2700K Warm White',
          ipRating: 'IP20 Indoor',
          installationType: 'Freestanding Table Lamp',
          beamAngle: '360° Diffuse',
          cri: 'Ra > 95',
          luminousFlux: '700 Lumens',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      {
        name: 'NL-TL102 Rattan Bedside Table Lamp',
        slug: 'nl-tl102-rattan-bedside-table-lamp',
        sku: 'NL-TL102',
        category: catMap['table-lamp'],
        shortDescription: 'Handwoven rattan drum table lamp with warm fabric inner lining for cosy bedroom lighting.',
        description: 'A natural, earthy accent for bedrooms and living rooms. The hand-woven rattan drum shade casts intricate geometric patterns on surrounding walls when illuminated.',
        images: [
          { url: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1200&q=80', alt: 'NL-TL102 Rattan Table Lamp', isCover: true },
        ],
        specifications: {
          dimensions: 'Height: 420mm, Shade Dia: 280mm',
          material: 'Rattan & Bamboo',
          finish: 'Natural Rattan',
          wattage: 'E27 Max 25W (Bulb Not Included)',
          voltage: 'AC 220-240V',
          colorTemperature: 'Depends on Bulb',
          ipRating: 'IP20 Indoor',
          installationType: 'Freestanding Table Lamp',
          beamAngle: '360° Textured Diffuse',
          cri: 'Depends on Bulb',
          luminousFlux: 'Depends on Bulb',
        },
        isFeatured: false,
        isPublished: true,
        sortOrder: 1,
      },
      // ── FLOOR LAMP ────────────────────────────────────────────────
      {
        name: 'NL-FL101 Arc Floor Lamp',
        slug: 'nl-fl101-arc-floor-lamp',
        sku: 'NL-FL101',
        category: catMap['floor-lamp'],
        shortDescription: 'Elegant arched floor lamp in brushed gold with a wide dome shade and inline dimmer.',
        description: 'The sweeping arc of the NL-FL101 projects over sofas, armchairs, and reading nooks, delivering a focused pool of warm light from above. The inline rotary dimmer allows you to set the perfect ambience.',
        images: [
          { url: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1200&q=80', alt: 'NL-FL101 Arc Floor Lamp', isCover: true },
        ],
        specifications: {
          dimensions: 'Height: 1800mm, Arc Reach: 1200mm, Base: 300mm',
          material: 'Steel & Aluminum',
          finish: 'Brushed Gold / Matte Black Shade Interior',
          wattage: 'E27 Max 40W (LED Bulb Included)',
          voltage: 'AC 220-240V',
          colorTemperature: '2700K Warm White',
          ipRating: 'IP20 Indoor',
          installationType: 'Freestanding Floor Lamp',
          beamAngle: '150° Downward',
          cri: 'Ra > 90',
          luminousFlux: '1200 Lumens',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      {
        name: 'NL-FL102 Tripod Walnut Floor Lamp',
        slug: 'nl-fl102-tripod-walnut-floor-lamp',
        sku: 'NL-FL102',
        category: catMap['floor-lamp'],
        shortDescription: 'Mid-century tripod floor lamp in walnut-finish wood legs with a linen drum shade.',
        description: 'The classic tripod silhouette with solid wood-effect legs in a warm walnut stain. The natural linen drum shade complements any Scandinavian, mid-century, or organic-modern interior.',
        images: [
          { url: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1200&q=80', alt: 'NL-FL102 Tripod Floor Lamp', isCover: true },
        ],
        specifications: {
          dimensions: 'Height: 1600mm, Shade Dia: 400mm',
          material: 'Solid Wood & Linen',
          finish: 'Walnut Stain / Natural Linen',
          wattage: 'E27 Max 40W (Bulb Not Included)',
          voltage: 'AC 220-240V',
          colorTemperature: 'Depends on Bulb',
          ipRating: 'IP20 Indoor',
          installationType: 'Freestanding Floor Lamp',
          beamAngle: '360° Diffuse',
          cri: 'Depends on Bulb',
          luminousFlux: 'Depends on Bulb',
        },
        isFeatured: false,
        isPublished: true,
        sortOrder: 1,
      },
      // ── LED FILAMENT BULB ─────────────────────────────────────────
      {
        name: 'NL-FB101 ST64 Edison LED Filament Bulb',
        slug: 'nl-fb101-st64-edison-led-filament-bulb',
        sku: 'NL-FB101',
        category: catMap['led-filament-bulb'],
        shortDescription: 'ST64 vintage Edison LED filament bulb 6W – warm 2200K amber glow, E27 base.',
        description: 'Recreates the warm, amber nostalgia of the original carbon filament lamp with 90% less energy consumption. The visible spiral LED filament is seen through the smoke-tinted globe for an authentic vintage aesthetic.',
        images: [
          { url: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1200&q=80', alt: 'NL-FB101 ST64 Filament Bulb', isCover: true },
        ],
        specifications: {
          dimensions: 'ST64: Dia 64mm, Height: 142mm',
          material: 'Glass & Tungsten Filament LED',
          finish: 'Smoke Tinted Globe',
          wattage: '6W LED (Equiv. 60W Incandescent)',
          voltage: 'AC 220-240V E27',
          colorTemperature: '2200K Sunset Amber',
          ipRating: 'IP20 Indoor',
          installationType: 'E27 Screw Base',
          beamAngle: '360° Omnidirectional',
          cri: 'Ra > 80',
          luminousFlux: '550 Lumens',
        },
        isFeatured: true,
        isPublished: true,
        sortOrder: 0,
      },
      {
        name: 'NL-FB102 G95 Globe LED Filament Bulb',
        slug: 'nl-fb102-g95-globe-led-filament-bulb',
        sku: 'NL-FB102',
        category: catMap['led-filament-bulb'],
        shortDescription: 'G95 large globe LED filament bulb 8W – clear glass, warm 2700K, E27 base.',
        description: 'The NL-FB102 features a 95mm diameter globe with a clear glass envelope showcasing the full spiral filament array. Perfect for exposed-bulb pendant lamps, industrial pendants, and decorative chandeliers.',
        images: [
          { url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80', alt: 'NL-FB102 G95 Globe Filament Bulb', isCover: true },
        ],
        specifications: {
          dimensions: 'G95: Dia 95mm, Height: 152mm',
          material: 'Clear Glass & LED Filament',
          finish: 'Clear Glass',
          wattage: '8W LED (Equiv. 75W Incandescent)',
          voltage: 'AC 220-240V E27',
          colorTemperature: '2700K Warm White',
          ipRating: 'IP20 Indoor',
          installationType: 'E27 Screw Base',
          beamAngle: '360° Omnidirectional',
          cri: 'Ra > 80',
          luminousFlux: '750 Lumens',
        },
        isFeatured: false,
        isPublished: true,
        sortOrder: 1,
      },
      {
        name: 'NL-FB103 T10 Tubular LED Filament Bulb',
        slug: 'nl-fb103-t10-tubular-led-filament-bulb',
        sku: 'NL-FB103',
        category: catMap['led-filament-bulb'],
        shortDescription: 'T10 tubular LED filament bulb 4W – vintage amber 2200K, ideal for bar cart and decorative holders.',
        description: 'The slender tubular form of the NL-FB103 is inspired by the original tubular incandescent. Perfect for exposed-bulb wall sconces, vintage bar pendants, and Edison-style lanterns.',
        images: [
          { url: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1200&q=80', alt: 'NL-FB103 Tubular Filament Bulb', isCover: true },
        ],
        specifications: {
          dimensions: 'T10: Dia 30mm, Height: 110mm',
          material: 'Clear Glass & LED Filament',
          finish: 'Clear / Amber Tint',
          wattage: '4W LED (Equiv. 40W Incandescent)',
          voltage: 'AC 220-240V E27',
          colorTemperature: '2200K Amber',
          ipRating: 'IP20 Indoor',
          installationType: 'E27 Screw Base',
          beamAngle: '360° Omnidirectional',
          cri: 'Ra > 80',
          luminousFlux: '400 Lumens',
        },
        isFeatured: false,
        isPublished: true,
        sortOrder: 2,
      },
      // ── HANGING BASE ──────────────────────────────────────────────
      {
        name: 'NL-SP101 Universal Ceiling Canopy Base',
        slug: 'nl-sp101-universal-ceiling-canopy-base',
        sku: 'NL-SP101',
        category: catMap['hanging-base'],
        shortDescription: 'Round ceiling canopy rose cover in brushed gold – fits all standard pendant and chandelier installations.',
        description: 'The NL-SP101 is a universal ceiling rose cover plate suitable for use with any pendant cord or chandelier suspension system. Its deep recess neatly conceals junction box wiring for a clean, professional finish.',
        images: [
          { url: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1200&q=80', alt: 'NL-SP101 Ceiling Canopy', isCover: true },
        ],
        specifications: {
          dimensions: 'Dia: 120mm, Depth: 55mm',
          material: 'Zinc Alloy',
          finish: 'Brushed Gold / Matte Black / Chrome',
          wattage: 'N/A (Spare Part)',
          voltage: 'N/A',
          colorTemperature: 'N/A',
          ipRating: 'IP20 Indoor',
          installationType: 'Ceiling Junction Box Cover',
          beamAngle: 'N/A',
          cri: 'N/A',
          luminousFlux: 'N/A',
        },
        isFeatured: false,
        isPublished: true,
        sortOrder: 0,
      },
      {
        name: 'NL-SP102 Large Square Ceiling Canopy 200mm',
        slug: 'nl-sp102-large-square-ceiling-canopy',
        sku: 'NL-SP102',
        category: catMap['hanging-base'],
        shortDescription: 'Square 200mm ceiling canopy for multi-cord chandelier and cluster pendant installations.',
        description: 'The NL-SP102 large square canopy is designed to house multiple pendant cords or chandelier cables from a single junction box. Available in matte black, brushed gold, and polished chrome finishes.',
        images: [
          { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', alt: 'NL-SP102 Square Canopy', isCover: true },
        ],
        specifications: {
          dimensions: '200mm x 200mm x 60mm',
          material: 'Zinc Alloy',
          finish: 'Matte Black / Brushed Gold / Chrome',
          wattage: 'N/A (Spare Part)',
          voltage: 'N/A',
          colorTemperature: 'N/A',
          ipRating: 'IP20 Indoor',
          installationType: 'Ceiling Junction Box Cover',
          beamAngle: 'N/A',
          cri: 'N/A',
          luminousFlux: 'N/A',
        },
        isFeatured: false,
        isPublished: true,
        sortOrder: 1,
      },
      // ── SPARE DRIVER ──────────────────────────────────────────────
      {
        name: 'NL-SP201 24V 60W Dimmable LED Driver',
        slug: 'nl-sp201-24v-60w-led-driver',
        sku: 'NL-SP201',
        category: catMap['spare-driver'],
        shortDescription: 'Constant-voltage 24V 60W dimmable LED driver – compatible with most NiceLamp LED products.',
        description: 'The NL-SP201 is a high-efficiency constant-voltage LED driver suitable as a replacement for failed drivers in NiceLamp LED chandeliers and pendant lamps. Built-in short-circuit, over-voltage, and over-temperature protection.',
        images: [
          { url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80', alt: 'NL-SP201 LED Driver', isCover: true },
        ],
        specifications: {
          dimensions: '180mm x 38mm x 30mm',
          material: 'Aluminum Housing',
          finish: 'Silver',
          wattage: '60W Output',
          voltage: 'Input: AC 100-240V / Output: 24V DC',
          colorTemperature: 'N/A',
          ipRating: 'IP20 Indoor',
          installationType: 'Internal Driver Replacement',
          beamAngle: 'N/A',
          cri: 'N/A',
          luminousFlux: 'N/A',
        },
        isFeatured: false,
        isPublished: true,
        sortOrder: 0,
      },
      {
        name: 'NL-SP202 12V 36W Constant Voltage LED Driver',
        slug: 'nl-sp202-12v-36w-led-driver',
        sku: 'NL-SP202',
        category: catMap['spare-driver'],
        shortDescription: '12V 36W constant voltage LED driver – replacement for NiceLamp 12V wall lamps and pendants.',
        description: 'The NL-SP202 is a compact 12V constant-voltage replacement driver for wall lamps and smaller pendant fixtures. Features active power factor correction (PFC) and a silent fanless cooling design.',
        images: [
          { url: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1200&q=80', alt: 'NL-SP202 12V LED Driver', isCover: true },
        ],
        specifications: {
          dimensions: '130mm x 35mm x 25mm',
          material: 'Aluminum Housing',
          finish: 'Silver',
          wattage: '36W Output',
          voltage: 'Input: AC 100-240V / Output: 12V DC',
          colorTemperature: 'N/A',
          ipRating: 'IP20 Indoor',
          installationType: 'Internal Driver Replacement',
          beamAngle: 'N/A',
          cri: 'N/A',
          luminousFlux: 'N/A',
        },
        isFeatured: false,
        isPublished: true,
        sortOrder: 1,
      },
    ];

    const createdProducts = await Product.insertMany(productsData);
    console.log('[Seed] Created products: ' + createdProducts.length);

    // 4. Seed Homepage Sections (Editable and Reorderable via Admin CMS)
    console.log('[Seed] Seeding homepage CMS sections...');
    const homepageSectionsData = [
      {
        sectionKey: 'hero',
        name: 'Hero Banner Section',
        title: 'Illuminating Architectural Masterpieces',
        subtitle: 'Decorative Solutions & Technical Precision',
        description: 'Pioneering contemporary architectural lighting fixtures, precision engineered wall luminaires, and bespoke statement chandeliers designed for world-class residential and commercial spaces.',
        images: [
          'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1920&q=85',
        ],
        buttonText: 'Explore Catalog',
        buttonLink: '/catalog',
        secondaryButtonText: 'Company Profile',
        secondaryButtonLink: '/about',
        isEnabled: true,
        order: 0,
        metadata: {
          badge: '2026 Architectural Catalog Edition',
          features: [
            'Die-Cast Aluminum Engineering',
            'Museum-Grade CRI > 95 Optics',
            'Bespoke Specifier Support',
          ],
        },
      },
      {
        sectionKey: 'categories',
        name: 'Curated Categories Showcase',
        title: 'Explore By Architectural Category',
        subtitle: 'Engineered For Every Space & Elevation',
        description: 'Navigate our comprehensive range of interior sconces, suspended pendants, sculptural task lamps, and exterior facade luminaires.',
        buttonText: 'View All Categories',
        buttonLink: '/catalog',
        isEnabled: true,
        order: 1,
      },
      {
        sectionKey: 'about',
        name: 'Company Profile & Craftsmanship',
        title: 'Precision Craftsmanship Meets Optical Mastery',
        subtitle: 'About NiceLamp Decorative Solutions',
        description: 'With decades of dedicated expertise in architectural illumination, NiceLamp manufactures and supplies premier lighting fixtures engineered for high-performance residential estates, boutique hotels, and landmark commercial pavilions.',
        images: [
          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80',
        ],
        buttonText: 'Read Full Company Profile',
        buttonLink: '/about',
        isEnabled: true,
        order: 2,
        metadata: {
          experienceYears: '25+',
          projectsCompleted: '1,200+',
          specifiers: '850+',
          gstNumber: '',
        },
      },
      {
        sectionKey: 'featured_products',
        name: 'Featured Luminaires Showcase',
        title: 'Curated Signature Fixtures',
        subtitle: 'Spotlight On Architectural Highlights',
        description: 'Hand-selected luminaires representing our highest echelon of optical engineering, material purity, and timeless form factor.',
        buttonText: 'Browse Full Catalog',
        buttonLink: '/catalog',
        isEnabled: true,
        order: 3,
      },
      {
        sectionKey: 'projects',
        name: 'Projects & Installation Showcase',
        title: 'Architectural Lighting In Practice',
        subtitle: 'Global Portfolios & Installed Excellence',
        description: 'From luxury seaside villas to prestigious hotel atriums, discover how our luminaires transform spatial aesthetics into immersive environments.',
        buttonText: 'View Portfolio',
        buttonLink: '/projects',
        isEnabled: true,
        order: 4,
        metadata: {
          portfolioItems: [
            {
              title: 'The Amanora Residence',
              location: 'New Delhi, India',
              category: 'Luxury Villa',
              image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
            },
            {
              title: 'Meridian Atrium & Spa',
              location: 'Mumbai, India',
              category: 'Hospitality',
              image: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1000&q=80',
            },
            {
              title: 'Horizon Business Pavilion',
              location: 'Bengaluru, India',
              category: 'Commercial Headquarters',
              image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80',
            },
          ],
        },
      },
      {
        sectionKey: 'cta',
        name: 'Inquiry CTA',
        title: 'Need Help Choosing the Right Light?',
        subtitle: 'Our Lighting Experts Are Ready to Help',
        description: 'Whether you need a single table lamp or a complete lighting solution for a hotel project, our team is here to assist with product selection, specifications, and pricing.',
        buttonText: 'Get a Quote',
        buttonLink: '/contact',
        secondaryButtonText: 'Browse Catalog',
        secondaryButtonLink: '/catalog',
        isEnabled: true,
        order: 5,
      },
      {
        sectionKey: 'contact',
        name: 'Showroom & Contact Details',
        title: 'Visit Our Showroom',
        subtitle: 'Experience the Collection in Person',
        description: 'Come and see our full range of lighting products on display at our showroom. Our team is available to help you find the perfect lighting for your home or project.',
        buttonText: 'Contact Us',
        buttonLink: '/contact',
        isEnabled: true,
        order: 6,
      },
    ];

    await HomepageSection.insertMany(homepageSectionsData);
    console.log('[Seed] Created homepage CMS sections.');

    // 5. Seed Site Settings
    console.log('[Seed] Seeding site-wide settings...');
    await SiteSettings.create({
      companyName: 'NiceLamp',
      tagline: 'Premium Decorative Lighting for Every Space',
      logo: '',
      favicon: '/favicon.svg',
      email: 'info@nicelamp.com',
      phone: '+91 9999000000',
      address: 'Shop No. 12, Light Market, Sadar Bazaar, Delhi, 110006, India',
      whatsapp: '+91 9999000000',
      socialLinks: {
        instagram: 'https://instagram.com/nicelamp',
        facebook: 'https://facebook.com/nicelamp',
        linkedin: 'https://linkedin.com/company/nicelamp',
        pinterest: 'https://pinterest.com/nicelamp',
      },
      footerContent: {
        copyrightText: '© 2026 NiceLamp. All Rights Reserved.',
        aboutText: 'NiceLamp is a premium decorative lighting brand offering wall lamps, chandeliers, pendants, table lamps, floor lamps, and outdoor lights for homes, hotels, and commercial spaces.',
        gstNumber: '',
      },
      defaultSeoTitle: 'NiceLamp | Premium Decorative Lighting – Wall Lamps, Chandeliers & More',
      defaultSeoDescription: 'Shop wall lamps, LED chandeliers, pendant lights, table lamps, floor lamps, and outdoor lights at NiceLamp – India\'s premium decorative lighting store.',
    });
    console.log('[Seed] Site settings created.');

    console.log('[Seed] ✅ NiceLamp catalog seeded successfully!');
    console.log(`[Seed] Categories: ${createdCategories.length}`);
    console.log(`[Seed] Products: ${createdProducts.length}`);
    if (isStandalone) {
      await mongoose.connection.close();
      process.exit(0);
    }
  } catch (error) {
    console.error('[Seed Error]:', error);
    if (isStandalone) process.exit(1);
    throw error;
  }
};

export const seedDatabase = seedAll;

const isDirectRun = process.argv[1] && (process.argv[1].endsWith('seedData.js') || process.argv[1].includes('seedData'));
if (isDirectRun) {
  seedAll(true);
}
